# Generated by Django 4.2.16 on 2025-01-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_bpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='catid',
        ),
    ]
