# Generated by Django 4.2.16 on 2025-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_issuedbookrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=100, unique=True)),
                ('cmsg', models.TextField()),
            ],
        ),
    ]
